# Generated by Django 4.1.1 on 2022-11-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
