# Generated by Django 4.2 on 2023-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datalist', '0002_alter_username_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='user',
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
